"""Initial migration

Revision ID: 3b7eecc4391b
Revises: 
Create Date: 2022-02-05 18:33:47.435264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7eecc4391b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_no', sa.String(length=6), nullable=False),
    sa.Column('job_no', sa.String(length=10), nullable=True),
    sa.Column('skid_no', sa.String(length=7), nullable=True),
    sa.Column('ed_no', sa.String(length=6), nullable=True),
    sa.Column('vin_no', sa.String(length=17), nullable=False),
    sa.Column('katashiki', sa.String(length=14), nullable=True),
    sa.Column('color', sa.String(length=25), nullable=True),
    sa.Column('m3', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('engine_no', sa.Integer(), nullable=True),
    sa.Column('engine_cap', sa.Integer(), nullable=True),
    sa.Column('container_no', sa.String(length=11), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vin')
    # ### end Alembic commands ###
