"""changing color column name

Revision ID: 4789acdccf84
Revises: 3b7eecc4391b
Create Date: 2022-02-06 23:01:28.471980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4789acdccf84'
down_revision = '3b7eecc4391b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vin', sa.Column('colour', sa.String(length=25), nullable=True))
    op.drop_column('vin', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vin', sa.Column('color', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_column('vin', 'colour')
    # ### end Alembic commands ###
